* the_pit --- A simple blog software that uses plaintext files

** HISTORY
For a lof of time, the person who wants a blog has been struggling
with the question on how the fuck to make a blog, "ssg? wordpress?"
And the_pit is the Final Solution to the Blog Question (in my opinion
at least)
** INSTALLATION
*** DEPENDENCES
- fcgi
- nginx
*** NGINX INSTALLATION    
It has been tested in nginx so this configuration is guaranteed to
work under nginx.

#+begin_src nginx
  location /blog { # Or any location you want
    try_files $uri $uri/ /blog/blog.cgi # This makes all requests go to the same file
  }

#+end_src
** FEATURES
- Runs on anything that runs perl and nginx
- Written in perl instead of python.
- RSS
- Depends on =CGI= only    
** HOW TO USE
After installing the_pit, you only drop files which have to have the
following naming scheme: =yyyymmdd.whatever.txt= "whatever" can be
whatever or can be nothing. Drop the files in the blogroot and the_pit
will do the rest.

You may edit the =footer.html= and =header.html= according to your
needs. And you can put whatever info you want in =notes.html=. These
files are hardcoded in the perl script.

